name: Publish
# on:
#   push:
#     branches:
#       - master
on: push
jobs:
  # storybook:
  #   name: Storybook
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - uses: ./.github/actions/setup
  #     - name: Publish Storybook to GitHub Pages
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         yarn run storybook:build
  #         yarn run deploy:ghp

  npm:
    name: NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup Git and NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git checkout master
          # git config --local user.name ${GIT_USER}
          # git config --locale user.email ${GIT_EMAIL}
          git remote set-url origin "https://${GITHUB_TOKEN}@github.com/airbnb/lunar.git" > /dev/null 2>&1
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      - name: Test
        run: |
          echo $GIT_AUTHOR_NAME
          echo $GIT_AUTHOR_EMAIL
          echo $GIT_COMMITTER_NAME
          echo $GIT_COMMITTER_EMAIL
          echo git config --get user.name
          echo git config --get user.email
      - uses: ./.github/actions/setup
      # Enable later on!
      # - name: Publish packages to NPM
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     yarn run deploy:npm
